language: node_js
node_js:
  - "10"

script: npm test

# Submit Coverage Status to coveralls.io
after_script:
  - cat ./test/coverage/lcov.info | ./node_modules/.bin/coveralls


deploy:
  provider: npm
  email: $NPM_AUTH_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    branch: release
