language: node_js
node_js:
- "8"

cache: yarn

install:
- yarn


before_script:
- yarn add global gulp

script: yarn run test

# Submit Coverage Status to coveralls.io
after_script:
- cat ./test/coverage/lcov.info | ./node_modules/.bin/coveralls
