name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Node CI
        run: |
          yarn install
          yarn test
          yarn build

  publish-npm:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: Node CI
        run: |
          yarn install
          yarn test
          yarn build
      - name: Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
